development:
  adapter: postgresql
  database: db/trucks

test:
  adapter: postgresql
  database: db/test

production:
  adapter: postgresql
  database: db/production
  pool: 5
  timeout: 5000

host: localhost